### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by pxxiao-hz** [cstritt/detettore#7]
Hello. When I use detettore, it has errors on some samples, as follows:
`Traceback (most recent call last):
  File "/public/home/pxxiao/software/Anaconda3/envs/detettore/bin/detettore", line 8, in <module>
    sys.exit(main())
  File "/public/home/pxxiao/software/Anaconda3/envs/detettore/lib/python3.7/site-packages/detettore.py", line 161, in main
    tips_vcf, tips_stats = tips.output_vcf(parameters)
  File "/public/home/pxxiao/software/Anaconda3/envs/detettore/lib/python3.7/site-packages/scripts/strumenti.py", line 414, in output_vcf
    gt_sr = get_genotype(ref_Q, alt_Q)
  File "/public/home/pxxiao/software/Anaconda3/envs/detettore/lib/python3.7/site-packages/scripts/strumenti.py", line 1723, in get_genotype
    GQ = round(Q_norm[1] - Q_norm[0])
ValueError: cannot convert float NaN to integer`

**Comment by cstritt** [comment]
Could you solve the issue? It has to do with the split reads, but I did not observe it so far...

**Comment by pxxiao-hz** [comment]
Sorry for the late reply. I haven't solved this yet. The bam file is a bit big and I don't know how to transfer it. Could you align it yourself?

One of the samples is [SRR10322135](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR10322135) and the reference genome is [http://citrus.hzau.edu.cn/data/Genome_info/SWO.v3.0/SWO.v3.0.genome.fa](http://citrus.hzau.edu.cn/data/Genome_info/SWO.v3.0/SWO.v3.0.genome.fa).

If you could‘t download it, please reply me at any time.

Best wishes.

**Comment by cstritt** [comment]
Excellent, I will take a look.

**Comment by cstritt** [comment]
I forgot, do you also have the TE consensus sequences? Then I would be ready to run the program

**Comment by pxxiao-hz** [comment]
[consensus.fa.classified.gz](https://github.com/cstritt/detettore/files/8109304/consensus.fa.classified.gz)
Yes, I have uploaded it. Please check it.
Thanks.

**Comment by cstritt** [comment]
Hello,
That's a nicely complicated genome you have there, with all the gene duplicates and apparent heterozygosity... My computer's memory was not quite up to the data, so troubleshooting took a bit longer. 

The program crashed at sites with massively elevated coverage (tandem repeats?). The new version 2.0.4, which I'll put online as a conda package as soon as I've figured out how to do this, has a filtering step removing these regions, so it should work now with all your samples. I will do few more tests and try to put it online this week.

So far detettore didn't ignore massive coverage regions because they could be easily spotted in the output vcf, but indeed there is no point in keeping them.

**Comment by pxxiao-hz** [comment]
I appreciate you doing these tests, thank you very much.

**Comment by acontrerasg** [comment]
Hello, 
Just  adding to this. I have the exact same problem.  I tried first  to  subsample my bam file to regions with normal coverage, but the error persisted. my genome is 512 mb with 61% TE content. Any solution yet? 
Thank you very much :D 


Edit: This only happens with the TIP module. The TAP module runs smoothly.

**Comment by cstritt** [comment]
Good morning @acontrerasg,
I couldn't quite find the time to work on this the past weeks, but now I have some. For the sample of @pxxiao-hz the error could be avoided by adding a coverage filtering step. The updated version is on the conda-release branch of detettore (it's not on conda yet, there's some polishing and testing to do...). Maybe you can try to run this on your normal, not subsampled bam?

**Comment by itossolini** [comment]
Hi! I have the same problem. Could you fix it?
I've just installed detettore following the installation instructions on readme.md #Create environment called detettore
It happens with some samples too.

**Comment by cstritt** [comment]
Good morning @itossolini ! The bug should be fixed in the development version of detettore. You can get this version by switching to the dev branch on github, then follow the installation steps described in the readme (this version is not on the pip respository). Let me know if you encounter problems.

**Comment by itossolini** [comment]
Thank you @cstritt for the quick response! I followed the installation steps in the dev branch, but I've got the error below:

```
Traceback (most recent call last):
  File "/home/itossolini/storage/TEPID/detettore/detettore/detettore.py", line 277, in <module>
    main()
  File "/home/itossolini/storage/TEPID/detettore/detettore/detettore.py", line 166, in main
    tips_vcf, tips_stats = tips.output_vcf(parameters)
  File "/share/storage/itossolini/TEPID/detettore/detettore/scripts/strumenti.py", line 574, in output_vcf
    PL = [ str(int(x)) if not math.isinf(x) else '1e6' for x in genotype[2] ]
  File "/share/storage/itossolini/TEPID/detettore/detettore/scripts/strumenti.py", line 574, in <listcomp>
    PL = [ str(int(x)) if not math.isinf(x) else '1e6' for x in genotype[2] ]
ValueError: cannot convert float NaN to integer
```

**Comment by cstritt** [comment]
Sorry for that, @itossolini , it should work now. If you stumble upon 'inf' or 'nan' values in your vcf output (for GQ and PL) and this poses a problem, let me know. These bugs never showed up with our _Brachypodium distachyon_ samples, so I'm still  not sure what's happening at these sites.

**Comment by itossolini** [comment]
It worked! Thank you so much! Yes, in fact I'm analyzing plant genomes which are not well assembled.

**Comment by Song-10-YF** [comment]
Hello, @cstritt 
I have the same problem.

"TIP search finished successfully


SEARCHING TE ABSENCE POLYMORPHISMS

Extracting read pairs around annotated TEs ...
Traceback (most recent call last):
  File "../detettore.py", line 277, in <module>
    main()
  File "../detettore.py", line 178, in main
    taps_vcf, taps_stats = taps.output_vcf(parameters)
  File "/home/songyf/Software/detettore/scripts/strumenti.py", line 961, in output_vcf
    GT, GQ, PL = get_genotype(ref_Q, alt_Q)
  File "/home/songyf/Software/detettore/scripts/strumenti.py", line 1724, in get_genotype
    GQ = round(Q_norm[1] - Q_norm[0])
OverflowError: cannot convert float infinity to integer"
I downloaded the software from dev branch.
My command is “python ../detettore.py -b Psubhirtella_modif.fasta.sort.bam -r Psubhirtella_modif.fasta -t Psub_TElib.fasta -a Psubhirtella_modif.fasta.out.gff -c 40 -o Psub -m tips taps --require_split --include_invariant”, and my comment file is from RepeatMasker.
